import 'package:flutter/material.dart';
import 'package:flutterapp/fashionapp/generatedstatusbaronlightwidget/generated/GeneratedWifiWidget.dart';
import 'package:flutterapp/fashionapp/generatedstatusbaronlightwidget/generated/GeneratedMobileSignalWidget.dart';
import 'package:flutterapp/fashionapp/generatedstatusbaronlightwidget/generated/GeneratedTimeStyleWidget.dart';
import 'package:flutterapp/fashionapp/generatedstatusbaronlightwidget/generated/GeneratedBatteryWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Instance Status Bar On Light
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStatusBarOnLightWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 31.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.06487474441528321;

                final double height =
                    constraints.maxHeight * 0.2575757118963426;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.895999993218316,
                      y: constraints.maxHeight * 0.3939394181774509,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedBatteryWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.04072634643978543;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 14.661484718322754;

                double percentHeight = 0.24921749484154485;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 7.725742340087891;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.841849856906467,
                      translateY: constraints.maxHeight * 0.3938793059318296,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedWifiWidget())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.04533332188924154;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 16.319995880126953;

                double percentHeight = 0.242424318867345;
                double scaleY =
                    (constraints.maxHeight * percentHeight) / 7.515153884887695;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.7831110636393229,
                      translateY: constraints.maxHeight * 0.40151466861847906,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedMobileSignalWidget())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.14400001102023655;

                final double height =
                    constraints.maxHeight * 0.47727264896515875;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.05599998897976345,
                      y: constraints.maxHeight * 0.2727269818705897,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedTimeStyleWidget(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
