import 'package:flutter/material.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedSpringWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedMostPopularWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedOurAppWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedSummerWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedGroup67Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle44Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedTabbarWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedAutumnWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedWinterWidget.dart';
import 'package:flutterapp/fashionapp/generatedandroidlarge1widget/generated/GeneratedRectangle47Widget.dart';

/* Frame Android Large - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(63, 0, 0, 0),
            offset: Offset(0.0, 4.0),
            blurRadius: 4.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0,
          height: 700.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(219, 252, 245, 255),
                  ),
                ),
                Positioned(
                  left: 10.0,
                  top: 36.0,
                  right: null,
                  bottom: null,
                  width: 328.0,
                  height: 24.0,
                  child: GeneratedGroup67Widget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 70.0,
                  right: null,
                  bottom: null,
                  width: 189.0,
                  height: 47.0,
                  child: GeneratedOurAppWidget(),
                ),
                Positioned(
                  left: 121.0,
                  top: 210.0,
                  right: null,
                  bottom: null,
                  width: 137.0,
                  height: 192.0,
                  child: GeneratedRectangle38Widget(),
                ),
                Positioned(
                  left: 280.0,
                  top: 238.0,
                  right: null,
                  bottom: null,
                  width: 137.0,
                  height: 192.0,
                  child: GeneratedRectangle43Widget(),
                ),
                Positioned(
                  left: -37.0,
                  top: 238.0,
                  right: null,
                  bottom: null,
                  width: 137.0,
                  height: 192.0,
                  child: GeneratedRectangle44Widget(),
                ),
                Positioned(
                  left: 23.0,
                  top: 458.0,
                  right: null,
                  bottom: null,
                  width: 174.63157653808594,
                  height: 34.0,
                  child: GeneratedMostPopularWidget(),
                ),
                Positioned(
                  left: 201.0,
                  top: 520.0,
                  right: null,
                  bottom: null,
                  width: 130.0,
                  height: 165.0,
                  child: GeneratedRectangle47Widget(),
                ),
                Positioned(
                  left: 33.0,
                  top: 520.0,
                  right: null,
                  bottom: null,
                  width: 130.0,
                  height: 165.0,
                  child: GeneratedRectangle51Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 640.0,
                  right: null,
                  bottom: null,
                  width: 360.0,
                  height: 60.0,
                  child: GeneratedTabbarWidget(),
                ),
                Positioned(
                  left: 13.0,
                  top: 133.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 41.000003814697266,
                  child: GeneratedRectangle34Widget(),
                ),
                Positioned(
                  left: 268.0,
                  top: 133.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 41.000003814697266,
                  child: GeneratedRectangle48Widget(),
                ),
                Positioned(
                  left: 183.0,
                  top: 132.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 41.000003814697266,
                  child: GeneratedRectangle49Widget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 133.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 41.000003814697266,
                  child: GeneratedRectangle50Widget(),
                ),
                Positioned(
                  left: 266.0,
                  top: 145.0,
                  right: null,
                  bottom: null,
                  width: 82.0,
                  height: 27.0,
                  child: GeneratedAutumnWidget(),
                ),
                Positioned(
                  left: 185.0,
                  top: 146.0,
                  right: null,
                  bottom: null,
                  width: 75.0,
                  height: 27.0,
                  child: GeneratedWinterWidget(),
                ),
                Positioned(
                  left: 10.0,
                  top: 146.0,
                  right: null,
                  bottom: null,
                  width: 74.88235473632812,
                  height: 27.0,
                  child: GeneratedSpringWidget(),
                ),
                Positioned(
                  left: 96.0,
                  top: 147.0,
                  right: null,
                  bottom: null,
                  width: 82.77777862548828,
                  height: 25.0,
                  child: GeneratedSummerWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
